### ISSUE TITLE
Error building for Web

### ISSUE THREAD

**Issue by Skquark** [asadbaidar/get_smart#2]
Been enjoying this addon, will use it in all future projects, thanks.  I just tried running the project on web, and I'm getting this error message:
```
.../get_smart-0.1.4]()+5/lib/src/widgets/app_bar.dart:198:61: Error: The integer literal 999999999999999999 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 1000000000000000000 is the nearest value that can be represented exactly.
            if (_largeTitle != null) _largeTitle.flex(flex: 999999999999999999),
                                                            ^^^^^^^^^^^^^^^^^^
```
Should be an easy fix, I could probably correct it myself and PR, but when I looked at that line it wasn't as obvious as I expected it to be.  Hope for a quick fix since I'd like to build to web soon.  Thanks...

**Comment by asadbaidar** [comment]
Fixed. Thanks for reporting and feel free for any PR if you think of some improvements. Have a great day.
https://pub.dev/packages/get_smart/changelog#0146
